apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-blue
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    color: blue
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      color: blue
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        color: blue
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tags.blue }}"
        ports:
        - containerPort: {{ .Values.port }}
        {{- if .Values.env }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}