apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-services
  namespace: monitoring
  labels:
    release: kube-prom
spec:
  namespaceSelector:
    matchNames:
    - apps
  selector:
    matchLabels:
      monitored: "true"
  endpoints:
  - port: http
    path: /metrics
    interval: 15s