apiVersion: v1
kind: Service
metadata:
  name: user-service-blue-internal
  namespace: apps
spec:
  selector:
    app: user-service
    color: blue
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-green-internal
  namespace: apps
spec:
  selector:
    app: user-service
    color: green
  ports:
  - port: 5000
    targetPort: 5000