apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-blue-internal
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
    color: blue
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-green-internal
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
    color: green
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}